extern void manage_deque(void);
extern void manage_compare(void);
extern void manage_any(void);
extern void manage_threads(void);
extern void manage_pthreads(void);
extern void manage_format(void);
extern void manage_time(void);
extern void manage_fstream(void);
extern void manage_concepts();
extern void manage_test(void);
extern void manage_ranges(void);
extern void manage_calc(void);
extern void manage_primzahl(unsigned long lower_limit, unsigned long upper_limit);
extern int manage_fractale(void);
extern int manage_sdl();
extern int manage_boost();
extern void manage_vcpkg(void);
